[package]
name = "sift-ffi"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
description = "C interface for embedded Sift search."

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
sift = { version = "0.1.0", path = "../sift", default-features = false }
serde_json.workspace = true
anyhow.workspace = true
